spring:
  application:
    name: sigesin-file-service
  profiles:
    active: dev
server:
  port: 2200

aws:
  credentials:
    access-key: ${SIGESIN_S3_ACCESS_KEY}
    secret-key: ${SIGESIN_S3_SECRET_KEY}
  s3:
    bucket-name: ${SIGESIN_S3_NAME}
    region: ${SIGESIN_S3_REGION}